from abc import ABC, abstractmethod
from typing import Any


class GroupOps(ABC):
    @abstractmethod
    async def send_group_msg(self, group_id: int, message: str, message_category: str = "command") -> Any: ...

    @abstractmethod
    async def delete_msg(self, message_id: int) -> None: ...

    @abstractmethod
    async def get_msg(self, message_id: int) -> dict[str, Any]: ...

    @abstractmethod
    async def mute(self, group_id: int, user_id: int, seconds: int) -> None: ...

    @abstractmethod
    async def unmute(self, group_id: int, user_id: int) -> None: ...

    @abstractmethod
    async def kick(self, group_id: int, user_id: int, reject_add_request: bool = False) -> None: ...

    @abstractmethod
    async def whole_mute(self, group_id: int, enable: bool) -> None: ...

    @abstractmethod
    async def set_group_card(self, group_id: int, user_id: int, card: str) -> None: ...

    @abstractmethod
    async def set_group_name(self, group_id: int, name: str) -> None: ...

    @abstractmethod
    async def set_group_admin(self, group_id: int, user_id: int, enable: bool) -> None: ...

    @abstractmethod
    async def set_group_anonymous(self, group_id: int, enable: bool) -> None: ...

    @abstractmethod
    async def set_special_title(self, group_id: int, user_id: int, title: str, duration: int = -1) -> None: ...

    @abstractmethod
    async def get_group_info(self, group_id: int, no_cache: bool = True) -> dict[str, Any]: ...

    @abstractmethod
    async def get_group_member_info(self, group_id: int, user_id: int, no_cache: bool = True) -> dict[str, Any]: ...

    @abstractmethod
    async def get_group_member_list(self, group_id: int) -> list[dict[str, Any]]: ...

    @abstractmethod
    async def handle_group_add_request(self, flag: str, sub_type: str, approve: bool, reason: str = "") -> None: ...
