DEFAULT_COMMAND_PREFIX = "/管"
PERMANENT_MUTE_SECONDS = 30 * 24 * 60 * 60
CARD_LOCK_EVENT_IGNORE_SECONDS = 10
CARD_LOCK_MAX_FAILURES = 3
CARD_LOCK_MAX_FIX_PER_SCAN = 50
CARD_LOCK_GROUP_RATE_LIMIT_SECONDS = 1.0
CARD_LOCK_MESSAGE_SCAN_INTERVAL_SECONDS = 30.0
DEFAULT_REASON = "未填写原因"
